//! macOS backend.
//!
//! `NSPasteboard` emits no change notification: Apple only provides
//! `changeCount`, an integer that increments. Polling is therefore not a
//! workaround here, it is the official API — and what every clipboard manager
//! on this platform does.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::mpsc::Sender;
use std::time::Duration;

use copycopy_core::ClipEvent;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardType, NSPasteboardTypeFileURL, NSPasteboardTypePNG,
    NSPasteboardTypeString, NSPasteboardTypeTIFF, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::{NSString, NSURL};

use crate::Capture;

const INTERVAL: Duration = Duration::from_millis(200);

/// Icons are normalised to this before they leave the backend: an application
/// icon arrives at whatever size its bundle ships, sometimes 1024 square, and
/// the interface draws it at a dozen pixels.
const ICON_SIZE: u32 = 32;

/// Conventions honoured by macOS password managers (1Password, Bitwarden and
/// friends) to ask that the content not be recorded in history.
const CONCEALED: &str = "org.nspasteboard.ConcealedType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";
const TRANSIENT: &str = "org.nspasteboard.TransientType";

pub fn spawn(tx: Sender<Capture>) -> Result<(), String> {
    std::thread::Builder::new()
        .name("copycopy-macos".into())
        .spawn(move || run(tx))
        .map_err(|e| e.to_string())?;
    Ok(())
}

fn run(tx: Sender<Capture>) {
    let pasteboard = NSPasteboard::generalPasteboard();
    let mut last_change = pasteboard.changeCount();
    let mut front = Frontmost::new();

    loop {
        std::thread::sleep(INTERVAL);

        // Read who is in front *before* looking at the clipboard, and at every
        // tick rather than only when something was copied: the answer then
        // predates the copy instead of following it, which is the difference
        // between naming the application that copied and naming the one the
        // user switched to afterwards.
        front.observe();

        let change = pasteboard.changeCount();
        if change == last_change {
            continue;
        }
        last_change = change;

        if is_secret(&pasteboard) {
            continue;
        }
        let Some(event) = read(&pasteboard) else {
            continue;
        };
        let (source, icon) = front.source();
        if tx
            .send(Capture {
                event,
                source,
                icon,
            })
            .is_err()
        {
            return; // L'UI est partie.
        }
    }
}

fn is_secret(pasteboard: &NSPasteboard) -> bool {
    let Some(types) = pasteboard.types() else {
        return false;
    };
    types.iter().any(|t| {
        let name = t.to_string();
        name == CONCEALED || name == AUTO_GENERATED || name == TRANSIENT
    })
}

/// The same check from outside this backend, for the polling fallback.
pub(crate) fn pasteboard_is_secret() -> bool {
    is_secret(&NSPasteboard::generalPasteboard())
}

fn read(pasteboard: &NSPasteboard) -> Option<ClipEvent> {
    // Files before pictures: Finder puts each copied file's *icon* beside its
    // URL, as PNG and TIFF. Pictures first kept a 1024×1024 generic icon and
    // lost the file. An application copying a picture puts no file URL.
    if let Some(paths) = read_file_urls(pasteboard) {
        if !paths.is_empty() {
            return Some(ClipEvent::Files(paths));
        }
    }

    // PNG first, then TIFF, which is what the system screenshot tool puts
    // there; it is converted back to PNG so only one format exists internally.
    let png_type: &NSPasteboardType = unsafe { NSPasteboardTypePNG };
    if let Some(data) = pasteboard.dataForType(png_type) {
        let png = data.to_vec();
        if !png.is_empty() {
            let size = crate::png_size(&png);
            return Some(ClipEvent::Image { png, size });
        }
    }
    let tiff_type: &NSPasteboardType = unsafe { NSPasteboardTypeTIFF };
    if let Some(data) = pasteboard.dataForType(tiff_type) {
        if let Some((png, size)) = tiff_to_png(&data.to_vec()) {
            return Some(ClipEvent::Image {
                png,
                size: Some(size),
            });
        }
    }

    let string_type: &NSPasteboardType = unsafe { NSPasteboardTypeString };
    let text = pasteboard.stringForType(string_type)?.to_string();
    if text.trim().is_empty() {
        return None;
    }
    Some(ClipEvent::Text(text))
}

/// Dragging several files in yields one pasteboard item per file.
fn read_file_urls(pasteboard: &NSPasteboard) -> Option<Vec<PathBuf>> {
    let items = pasteboard.pasteboardItems()?;
    let url_type: &NSPasteboardType = unsafe { NSPasteboardTypeFileURL };
    let paths: Vec<PathBuf> = items
        .iter()
        .filter_map(|item| item.stringForType(url_type))
        .map(|s| url_to_path(&s.to_string()))
        .collect();
    Some(paths)
}

/// Finder copies file *reference* URLs — `file:///.file/id=6571367.918776` —
/// which name an inode, not a path. Stripping the scheme stored that as the
/// path, so every file copied from Finder showed as a dead `/.file/id=…`.
/// `filePathURL` resolves a reference and leaves a plain file URL as it is.
fn url_to_path(url: &str) -> PathBuf {
    NSURL::URLWithString(&NSString::from_str(url))
        .and_then(|u| u.filePathURL())
        .and_then(|u| u.path())
        .map(|p| PathBuf::from(p.to_string()))
        .unwrap_or_else(|| {
            PathBuf::from(crate::percent_decode(
                url.strip_prefix("file://").unwrap_or(url),
            ))
        })
}

fn tiff_to_png(tiff: &[u8]) -> Option<(Vec<u8>, (u32, u32))> {
    let decoded = image::load_from_memory_with_format(tiff, image::ImageFormat::Tiff).ok()?;
    let size = (decoded.width(), decoded.height());
    let mut png = Vec::new();
    decoded
        .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
        .ok()?;
    Some((png, size))
}

/// Who to credit a copy to.
///
/// `NSPasteboard` carries no owner — unlike an X11 selection, which belongs to
/// a window, or the Windows clipboard, which answers `GetClipboardOwner`. Every
/// clipboard manager on this platform therefore credits the application that
/// was in front when `changeCount` moved, and so does this one.
///
/// It is a guess, and the one case it gets wrong is worth stating: copy, then
/// switch application within the polling interval, and the copy is credited to
/// the application you switched to. Observing at every tick keeps that window
/// to the 200 ms it cannot avoid.
struct Frontmost {
    /// Our own bundle identifier. The window opens in front of everything, so
    /// without this copycopy would end up crediting itself.
    us: Option<String>,
    /// The last application seen in front that was not us: its identifier, and
    /// the name to show.
    current: Option<(String, String)>,
    /// One icon per application, converted once. The same bytes then travel
    /// with every capture from that source; the interface keeps one copy.
    icons: HashMap<String, Option<Vec<u8>>>,
}

impl Frontmost {
    fn new() -> Self {
        Self {
            us: NSRunningApplication::currentApplication()
                .bundleIdentifier()
                .map(|id| id.to_string()),
            current: None,
            icons: HashMap::new(),
        }
    }

    fn observe(&mut self) {
        let Some(app) = NSWorkspace::sharedWorkspace().frontmostApplication() else {
            return;
        };
        // No bundle identifier: a process with no `Info.plist`, which the name
        // alone still identifies well enough to key an icon on.
        let id = app
            .bundleIdentifier()
            .map(|id| id.to_string())
            .or_else(|| app.localizedName().map(|n| n.to_string()));
        let Some(id) = id else { return };
        if self.us.as_deref() == Some(id.as_str()) {
            return;
        }
        let name = app
            .localizedName()
            .map(|n| n.to_string())
            .unwrap_or_else(|| id.clone());

        if !self.icons.contains_key(&id) {
            let png = icon_png(&app);
            let _ = self.icons.insert(id.clone(), png);
        }
        self.current = Some((id, name));
    }

    fn source(&self) -> (String, Option<Vec<u8>>) {
        match &self.current {
            Some((id, name)) => (
                name.clone(),
                self.icons.get(id).cloned().unwrap_or_default(),
            ),
            None => (String::new(), None),
        }
    }
}

/// The application's icon as a small PNG.
///
/// Through TIFF rather than AppKit's drawing APIs: `NSImage` would have to be
/// redrawn into a sized context, which drags in graphics contexts and their
/// main-thread rules, while this crate already decodes TIFF and encodes PNG for
/// the clipboard itself.
fn icon_png(app: &NSRunningApplication) -> Option<Vec<u8>> {
    let tiff = app.icon()?.TIFFRepresentation()?.to_vec();
    let decoded = image::load_from_memory_with_format(&tiff, image::ImageFormat::Tiff).ok()?;
    let small = decoded.resize_exact(
        ICON_SIZE,
        ICON_SIZE,
        image::imageops::FilterType::CatmullRom,
    );
    let mut png = std::io::Cursor::new(Vec::new());
    small.write_to(&mut png, image::ImageFormat::Png).ok()?;
    Some(png.into_inner())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finder_file_references_resolve_to_paths() {
        let path = std::env::current_exe().unwrap().canonicalize().unwrap();
        let url = NSURL::fileURLWithPath(&NSString::from_str(path.to_str().unwrap()));
        let reference = url.fileReferenceURL().unwrap().absoluteString().unwrap();
        assert!(reference.to_string().contains("/.file/id="));
        assert_eq!(
            url_to_path(&reference.to_string()).canonicalize().unwrap(),
            path
        );
    }
}
