//! Backend macOS.
//!
//! `NSPasteboard` n'émet aucune notification de changement : Apple ne fournit
//! que `changeCount`, un entier qui s'incrémente. Le sondage n'est donc pas un
//! pis-aller ici, c'est l'API officielle — c'est ce que font tous les
//! gestionnaires de presse-papier sur cette plateforme.

use std::path::PathBuf;
use std::sync::mpsc::Sender;
use std::time::Duration;

use copycopy_core::ClipEvent;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardType, NSPasteboardTypeFileURL, NSPasteboardTypePNG,
    NSPasteboardTypeString, NSPasteboardTypeTIFF,
};
use objc2_foundation::NSString;

use crate::Capture;

const INTERVAL: Duration = Duration::from_millis(200);

/// Conventions respectées par les gestionnaires de mots de passe macOS
/// (1Password, Bitwarden…) pour demander de ne pas historiser le contenu.
const CONCEALED: &str = "org.nspasteboard.ConcealedType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";
const TRANSIENT: &str = "org.nspasteboard.TransientType";

pub fn spawn(tx: Sender<Capture>) -> Result<(), String> {
    std::thread::Builder::new()
        .name("copycopy-macos".into())
        .spawn(move || run(tx))
        .map_err(|e| e.to_string())?;
    Ok(())
}

fn run(tx: Sender<Capture>) {
    let pasteboard = NSPasteboard::generalPasteboard();
    let mut last_change = pasteboard.changeCount();

    loop {
        std::thread::sleep(INTERVAL);

        let change = pasteboard.changeCount();
        if change == last_change {
            continue;
        }
        last_change = change;

        if is_secret(&pasteboard) {
            continue;
        }
        let Some(event) = read(&pasteboard) else {
            continue;
        };
        if tx
            .send(Capture {
                event,
                // macOS n'expose pas l'application qui a écrit dans le
                // presse-papier : `NSPasteboard` ne porte pas cette information.
                source: String::new(),
            })
            .is_err()
        {
            return; // L'UI est partie.
        }
    }
}

fn is_secret(pasteboard: &NSPasteboard) -> bool {
    let Some(types) = pasteboard.types() else {
        return false;
    };
    types.iter().any(|t| {
        let name = t.to_string();
        name == CONCEALED || name == AUTO_GENERATED || name == TRANSIENT
    })
}

fn read(pasteboard: &NSPasteboard) -> Option<ClipEvent> {
    // PNG d'abord, puis TIFF (ce que pose la capture d'écran système), qu'on
    // reconvertit en PNG pour n'avoir qu'un seul format en interne.
    let png_type: &NSPasteboardType = unsafe { NSPasteboardTypePNG };
    if let Some(data) = pasteboard.dataForType(png_type) {
        let png = data.to_vec();
        if !png.is_empty() {
            let size = crate::png_size(&png);
            return Some(ClipEvent::Image { png, size });
        }
    }
    let tiff_type: &NSPasteboardType = unsafe { NSPasteboardTypeTIFF };
    if let Some(data) = pasteboard.dataForType(tiff_type) {
        if let Some((png, size)) = tiff_to_png(&data.to_vec()) {
            return Some(ClipEvent::Image {
                png,
                size: Some(size),
            });
        }
    }

    if let Some(paths) = read_file_urls(pasteboard) {
        if !paths.is_empty() {
            return Some(ClipEvent::Files(paths));
        }
    }

    let string_type: &NSPasteboardType = unsafe { NSPasteboardTypeString };
    let text = pasteboard.stringForType(string_type)?.to_string();
    if text.trim().is_empty() {
        return None;
    }
    Some(ClipEvent::Text(text))
}

/// Un glisser-déposer de plusieurs fichiers donne un élément par fichier.
fn read_file_urls(pasteboard: &NSPasteboard) -> Option<Vec<PathBuf>> {
    let items = pasteboard.pasteboardItems()?;
    let url_type: &NSPasteboardType = unsafe { NSPasteboardTypeFileURL };
    let paths: Vec<PathBuf> = items
        .iter()
        .filter_map(|item| item.stringForType(url_type))
        .map(|s| url_to_path(&s.to_string()))
        .collect();
    Some(paths)
}

fn url_to_path(url: &str) -> PathBuf {
    PathBuf::from(crate::percent_decode(
        url.strip_prefix("file://").unwrap_or(url),
    ))
}

fn tiff_to_png(tiff: &[u8]) -> Option<(Vec<u8>, (u32, u32))> {
    let decoded = image::load_from_memory_with_format(tiff, image::ImageFormat::Tiff).ok()?;
    let size = (decoded.width(), decoded.height());
    let mut png = Vec::new();
    decoded
        .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
        .ok()?;
    Some((png, size))
}

/// Petit garde-fou : si un jour `NSString` change de représentation, on veut
/// que ça pète à la compilation et pas silencieusement à l'exécution.
#[allow(dead_code)]
fn _assert_string_api(s: &NSString) -> String {
    s.to_string()
}
