[package]
name = "copycopy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "copycopy"
path = "src/main.rs"

[dependencies]
copycopy-core = { path = "../core" }
copycopy-platform = { path = "../platform" }
iced = { version = "0.14", features = ["advanced", "tokio", "canvas"] }
image = { version = "0.25", default-features = false, features = ["png"] }
global-hotkey = "0.8"
interprocess = "2.4"
directories = "6"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.13", default-features = false, features = ["tokio"] }
